name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      # Example deployment to Vercel
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: '--prod'

      # Alternative: Deploy to other platforms
      # - name: Deploy to AWS
      #   run: |
      #     # Add your AWS deployment commands here
      #     echo "Deploying to AWS..."

      # - name: Deploy to Azure
      #   run: |
      #     # Add your Azure deployment commands here
      #     echo "Deploying to Azure..."

      # - name: Deploy to Google Cloud
      #   run: |
      #     # Add your GCP deployment commands here
      #     echo "Deploying to Google Cloud..." 